### ISSUE TITLE
Uncaught TypeError: Failed to execute 'add' on 'HTMLSelectElement': The provided value is not of type '(HTMLOptionElement or HTMLOptGroupElement)'

### ISSUE THREAD

**Issue by patrickmaciel** [nbubna/HTML#21]
I'm trying to add a select with some options inside a `td` but I get the follow error:

```
Uncaught TypeError: Failed to execute 'add' on 'HTMLSelectElement': The provided value is not of type '(HTMLOptionElement or HTMLOptGroupElement)'
```

This is a piece of my code:

```
extraTd = tr.add('td');
var element = extraTd.add('select.ui.selection.dropdown.');
element.each('name', input_name + '[' + id + '][reference]');
element.add('option[value=0]').textContent = 'Não';
element.add('option[value=1]').textContent = 'Sim';
```

---

If you need more information tell me.

**Comment by nbubna** [comment]
Sorry for the slow response. I've got a new baby.

Turns out that HTMLSelectElement has a native `add(item[, before])`

HTML.js makes a practice of not overriding native methods.  Let me see if i can think of an easy workaround that still lets you use the emmet syntax after i get some caffeine in me.

Also, you might consider switching to my planned successor for HTML.js: [DOMx](http://esha.github.io/domx/#append%28%29). It takes a lot of similar concepts and ways of working directly with the DOM but gives them more reliable implementations and more thought-out APIs.

**Comment by patrickmaciel** [comment]
Congrats my friend! I hope everything it's ok :)

I will test this "DOMx".

Anyway, thanks for your time :+1:

**Comment by nbubna** [comment]
Got it. Just use `HTML.add.create`:

```
extraTd = tr.add('td');
var element = extraTd.add('select.ui.selection.dropdown.');
element.each('name', input_name + '[' + id + '][reference]');
HTML.add.create(element, 'option[value=0]').textContent = 'Não';
HTML.add.create(element, 'option[value=1]').textContent = 'Sim';
```

**Comment by nbubna** [comment]
That really should have occurred to me sooner. I blame sleeplessness. :)
