### ISSUE TITLE
document is terrible

### ISSUE THREAD

**Issue by chaegumi** [nbubna/HTML#23]
I can not know, how to do like this 

``` php

$("<div><p>Hello</p></div>")

```

or like simple html dom

str_get_html

**Comment by nbubna** [comment]
Not sure what you mean by "like simple html dom str_get_html", but the previous sample isn't something for which HTML.js provides any shortcuts. You can use the standard DOM functions, though:

``` javascript
var div = document.createElement('div');
div.innerHTML = '<p>Hello</p>';
```

Or, if you have to use the same exact string of markup and want a handy function, that returns an HTML.js ready result, you could write something like this:

``` javascript
HTML.create = function(markup) {
  var div = document.createElement('div');
  div.innerHTML = markup;
  return HTML.ify(div.children.length > 1 ? div.children : div.children[0]);
};

HTML.create('<div><p>Hello</p></div>');
```

Just don't expect one-to-one feature parity with jQuery. HTML.js (and DOMx, its successor) exist to enhance the native DOM and encourage you to learn and use that, instead of a wrapping API like jQuery. It's not always as concise, of course, but it'll make you a better web developer.

**Comment by chaegumi** [comment]
thanks,
simple_html_dom is A HTML DOM parser written in PHP5+ let you manipulate HTML in a very easy way.

can use like

``` php

// Create a DOM object from a string
$html = str_get_html('<html><body>Hello!</body></html>');

// Create a DOM object from a URL
$html = file_get_html('http://www.google.com/');

// Create a DOM object from a HTML file
$html = file_get_html('test.htm');

```

**Comment by chaegumi** [comment]
thanks,
simple_html_dom is A HTML DOM parser written in PHP5+ let you manipulate HTML in a very easy way.

can use like

```php

// Create a DOM object from a string
$html = str_get_html('<html><body>Hello!</body></html>');

// Create a DOM object from a URL
$html = file_get_html('http://www.google.com/');

// Create a DOM object from a HTML file
$html = file_get_html('test.htm');

```

**Comment by chaegumi** [comment]
thanks,
simple_html_dom is A HTML DOM parser written in PHP5+ let you manipulate HTML in a very easy way.

can use like

```php

// Create a DOM object from a string
$html = str_get_html('<html><body>Hello!</body></html>');

// Create a DOM object from a URL
$html = file_get_html('http://www.google.com/');

// Create a DOM object from a HTML file
$html = file_get_html('test.htm');

```

**Comment by chaegumi** [comment]
thanks,
simple_html_dom is A HTML DOM parser written in PHP5+ let you manipulate HTML in a very easy way.

can use like

```php

// Create a DOM object from a string
$html = str_get_html('<html><body>Hello!</body></html>');

// Create a DOM object from a URL
$html = file_get_html('http://www.google.com/');

// Create a DOM object from a HTML file
$html = file_get_html('test.htm');

```
